//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    
    public partial class brand
    {

        
        public int ID { get; set; }
        [StringLength(25, ErrorMessage = "Không được nhập quá 255 ký tự")]
        [DisplayName("Tên thương hiệu")]
        [Required(ErrorMessage = "Bạn phải nhập đầy đủ tên thương hiệu" )]
        public string BrandName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Star { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public string Image { get; set; }
        public string Link { get; set; }
        public Nullable<int> Products { get; set; }
    }
}
