//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category_brand
    {
        public int id { get; set; }
        public Nullable<int> Category_Brand_ID { get; set; }
        public Nullable<int> BrandID { get; set; }
    }
}
