//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eshopperEntities : DbContext
    {
        public eshopperEntities()
            : base("name=eshopperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<productdetail> productdetails { get; set; }
        public virtual DbSet<productimage> productimages { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<sociallink> sociallinks { get; set; }
        public virtual DbSet<webconfig> webconfigs { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<category_brand> category_brand { get; set; }
        public virtual DbSet<producttype> producttypes { get; set; }
        public virtual DbSet<condition> conditions { get; set; }
        public virtual DbSet<product> products { get; set; }
    }
}
