//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class product
    {
        public int ID { get; set; }
        [StringLength(255, ErrorMessage = "Không được nhập quá 255 ký tự")]
        [DisplayName("Tên sản phẩm")]
        [Required(ErrorMessage = "Bạn phải nhập đầy đủ tên sản phẩm")]
        public string Name { get; set; }

        [DisplayName("Ngày nhập")]
        public Nullable<System.DateTime> DateImport { get; set; }

        [DisplayName("Giá bán")]
        public Nullable<int> Price { get; set; }
        
        [DisplayName("Điểm đánh giá")]
        public Nullable<int> Stars { get; set; }

        [DisplayName("Thương hiệu")]
        [Required(ErrorMessage = "Bạn phải chọn tên thương hiệu")]
        public Nullable<int> Brands { get; set; }

        [DisplayName("Trạng thái")]
        [Required(ErrorMessage = "Bạn phải chọn trạng thái sản phẩm")]
        public Nullable<int> Condition { get; set; }
        
        [DisplayName("Hình ảnh sản phẩm")]
        public string MainImage { get; set; }
        
        [DisplayName("Hiển thị")]
        public bool Status { get; set; }
        
        [DisplayName("Loại sản phẩm")]
        public Nullable<int> ProductTypeID { get; set; }
    }
}
