//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webconfig
    {
        public int id { get; set; }
        public string ImageServer { get; set; }
        public string FavIcon { get; set; }
        public string Logo { get; set; }
        public string WebName { get; set; }
    }
}
